### PR TITLE
Updated dependencies, nightly toolchain

### PR DESCRIPTION
**Pull request by domenukk**

### CODE REVIEW

**Comment by domenukk** [comment]
Couldn't update rand to 0.8, since https://github.com/eqv/loaded_dice depends on 0.7

**Comment by domenukk** [comment]
After https://github.com/eqv/loaded_dice/pull/1 gets merged we can update the rand version, too

**Comment by andreafioraldi** [comment]
Is the PR ready? Can I merge?

**Comment by domenukk** [comment]
Now it is

**Comment by domenukk** [comment]
or wait

**Comment by andreafioraldi** [comment]
Have you tested that the fuzzer component works, maybe with the mruby example?

**Comment by domenukk** [comment]
I didn't change the behavior, just fixed bugs

**Comment by domenukk** [comment]
(and cannot test it on MacOS, shmem fails)

**Comment by andreafioraldi** [comment]
Merged as I tested it on Ubuntu 20 and the fuzzer runs

**Comment by andreafioraldi** [comment]
Tomorrow I'll bump the versions to 0.1.1 (@domenukk did you change any API? It doesn't seem but maybe I missed something) and update crates.io

**Comment by domenukk** [comment]
Yes the API changed accidently, as it now depends on Rand 0.8

**Pull request merged**
